_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
